version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  users-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_NAME: usersdb
    depends_on:
      - postgres
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
